# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: llacsivy <llacsivy@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/11 12:01:07 by llacsivy          #+#    #+#              #
#    Updated: 2024/10/11 12:16:50 by llacsivy         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS		:= 	../sources/maths/tuple_1.c \
				../sources/maths/tuple_2.c \
				../sources/maths/tuple_3.c

test :
	cc ./tests_vector_maths.c $(SRCS) -o tests_vector_maths
	./tests_vector_maths
	rm -f ./tests_vector_maths